FROM ubuntu:20.04

ENV BUILDIR /build

ENV \
    DEBIAN_FRONTEND=noninteractive \
    LC_ALL=C.UTF-8 \
    CFLAGS=-O0 

RUN set -eux; \
    apt-get update; \
        apt-get install -y --no-install-recommends \
        tar \
        lcov \
        pkg-config \
        git \
        libicu-dev \
        python3 \
        libpython3-dev  \
        libreadline-dev \
        zlib1g-dev \
        libev-dev \
        libkrb5-dev \
        libssl-dev \
        libxml2-dev \
        libxslt-dev \
        libldap-dev \
        gettext \
        tcl \
        tcl-dev \
        perl \
        libperl-dev \
        libipc-run-perl \
        build-essential \
        flex \
        bison \
        systemd-sysv libicu66 libev4 libpam0g libssl1.1 libxml2 libxml2-utils xsltproc tzdata docbook-xsl \
        ssl-cert locales dbus-x11 libipc-run-perl \
        vim \
        gdb \
    && apt-get clean all;
