FROM etcd:latest as myetcd

RUN echo 1

FROM pgbuildenv as sdmbuilder

ENV \
    BUILDIR=/build \
    DEBIAN_FRONTEND=noninteractive \
    LC_ALL=C.UTF-8 \
    CFLAGS=-O0 

WORKDIR $BUILDIR
COPY shardman $BUILDIR/shardman
WORKDIR $BUILDIR/shardman

RUN ./configure --enable-debug \
    --enable-cassert \
    --enable-nls \
    --with-perl \
    --with-python \
    --with-tcl \
    --with-gssapi \
    --with-openssl \
    --with-libxml \
    --with-libxslt \
    --with-ldap \
    --with-icu \
    --with-tclconfig=/usr/lib/tcl8.6

RUN make -s -j4 install \
    && make -s -C contrib install \ 
    && GIT_SSL_NO_VERIFY=1 git clone --depth 1 --branch REL_2_5 https://github.com/postgrespro/pg_probackup.git contrib/pg_probackup \
    && cd contrib/pg_probackup \
    && make && make install

FROM gobuilder:latest

ARG PG_MAJOR={{ PgMajor }}

ENV APP=/opt/pgpro/sdm-$PG_MAJOR \
    BUILDIR=/build

COPY --from=sdmbuilder /usr/lib/x86_64-linux-gnu/libicu* /usr/lib/x86_64-linux-gnu
COPY --from=sdmbuilder /usr/local/pgsql $APP
COPY --from=sdmbuilder /build/shardman /build/shardman
COPY --from=sdmbuilder /build/shardman/src/interfaces/libpq/libpq.so* /usr/lib/x86_64-linux-gnu
COPY --from=myetcd /opt/pgpro/etcd/bin/etcd $APP/bin/etcd
COPY shardman-utils $BUILDIR/shardman-utils

RUN mkdir -p /etc/shardman


RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gnupg \
    curl \
    ca-certificates \
    vim \
    && echo "deb [arch=amd64] http://repo.postgrespro.ru/pg_probackup/deb focal main-focal" > /etc/apt/sources.list.d/probackup.list \
    && curl -fsSL http://repo.postgrespro.ru/pg_probackup/keys/GPG-KEY-PG_PROBACKUP | apt-key add - \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt -y install systemd-sysv \
    libev4 \
    libicu66 \
    libldap-2.4-2 \
    libpam0g \
    libssl1.1 \
    libxml2 \
    tzdata \
    ssl-cert \
    locales \
    dbus-x11 \
    make \
    libipc-run-perl \
    libreadline8 \
    pkg-config \
    zlib1g \
    git \
    rsyslog \
    openssh-client \
    openssh-server \
    tar \
    gdb \
    pg-probackup-$PG_MAJOR \
    && apt-get purge -y --allow-remove-essential --allow-change-held-packages \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && grep ^postgres: /etc/group || groupadd postgres \
    && grep ^postgres: /etc/passwd && usermod -s /bin/bash postgres \
    || useradd -M -N -g postgres -r -d /var/lib/postgresql -s /bin/bash -c "Postgres Pro Server" postgres \
    && chown postgres:postgres /etc/shardman -R \
    && chown postgres:postgres /opt/pgpro -R \
    && chown postgres:postgres /build -R \
    && touch /var/log/postgres.log \
    && chown postgres:postgres /var/log/postgres.log \
    && mkdir -p $APP/data \
    && printf "postgres ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers \
    && mkdir -p /var/lib/postgresql

RUN apt-get update && apt-get install -y libxml2 less 

RUN mkdir -p /var/lib/pgpro/sdm-${PG_MAJOR}/data  

ENV PATH "/opt/pgpro/sdm-$PG_MAJOR/bin:${PATH}"
ENV LD_LIBRARY_PATH "/opt/pgpro/sdm-$PG_MAJOR/lib:/usr/lib/x86_64-linux-gnu"
RUN ldconfig /opt/pgpro/sdm-$PG_MAJOR/lib:/usr/lib/x86_64-linux-gnu

WORKDIR /build/shardman-utils
RUN --mount=type=cache,target=/go/pkg go mod tidy && make

ENTRYPOINT ["/goloop/goloop"]
