# syntax={{ DockerSyntax }}
FROM pgbuildenv

ENV \
  BUILDIR=/build \
  LC_ALL=C.UTF-8 \
  CFLAGS=-O0 

RUN <<-EOF
  grep ^postgres: /etc/group || groupadd postgres
  grep ^postgres: /etc/passwd 
  usermod -s /bin/bash postgres || useradd -M -N -g postgres -r -d /var/lib/postgresql -s /bin/bash -c "Postgres Pro Server" postgres
  usermod -aG sudo postgres
  echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
  mkdir -p /repo
  chown postgres:postgres /repo -R
  cpan -i -T -f Fuse
EOF

COPY --from=gobuilder:latest /goloop/goloop /goloop/goloop

ENTRYPOINT ["/goloop/goloop"]
