# syntax=docker/dockerfile:1
FROM gobuilder:latest as gbuilder

ENV BUILDIR /build

RUN mkdir $BUILDIR

WORKDIR $BUILDIR
COPY shardman-utils $BUILDIR/shardman-utils
WORKDIR $BUILDIR/shardman-utils

RUN --mount=type=cache,target=/go/pkg \
    go mod tidy && {{ Build }}

FROM {{ ImageSdmNode }}

ARG PG_MAJOR={{ PgMajorVersion }}
ARG SDM_CLUSTER_NAME={{ ClusterName }}
ARG SDM_LOG_LEVEL={{ ClusterLogLevel }}
ARG SDM_STORE_ENDPOINTS={{ EtcdList }}

ENV APP /opt/pgpro/sdm-$PG_MAJOR

COPY sdmspec.json /etc/shardman
COPY --chown=postgres:postgres generate.sql /var/lib/postgresql
COPY --from=gbuilder /build/shardman-utils/bin/ $APP/bin
{{ CopyDebugTool }}

RUN <<-EOF
  mkdir -p /var/lib/pgpro/sdm-14/data

  # Set SDM env vars
cat > /etc/shardman/shardmand-${SDM_CLUSTER_NAME}.env <<- EOFVARS
SDM_CLUSTER_NAME=${SDM_CLUSTER_NAME}
SDM_LOG_LEVEL=${SDM_LOG_LEVEL}
SDM_STORE_ENDPOINTS=${SDM_STORE_ENDPOINTS}
EOFVARS
EOF

EXPOSE 15432
EXPOSE 5432
EXPOSE 5433
EXPOSE 5442
EXPOSE 5443

WORKDIR /

CMD ["/bin/bash", "-c", "exec /sbin/init --log-color=true --log-level=info --log-target=console 3>&1"]
