# syntax={{ DockerSyntax }}
FROM grafana/grafana

ADD datasource.yaml /etc/grafana/provisioning/datasources/
ADD dashboard.yaml /etc/grafana/provisioning/dashboards/
ADD Main.json /etc/grafana/provisioning/dashboards/
