FROM ubuntu:20.04

ARG PG_MAJOR={{ PgMajor }}
ENV APP /opt/pgpro/sdm-$PG_MAJOR

RUN mkdir -p /etc/systemd/system/systemd-logind.service.d /etc/shardman /build /mntdata && chmod -R 0777 /mntdata

RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gnupg \
    curl \
    ca-certificates \
    vim \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt -y install systemd-sysv \
    libev4 \
    libicu66 \
    libldap-2.4-2 \
    libpam0g \
    libssl1.1 \
    libxml2 \
    tzdata \
    ssl-cert \
    locales \
    dbus-x11 \
    make \
    libipc-run-perl \
    libyaml-libyaml-perl \
    libreadline8 \
    pkg-config \
    zlib1g \
    git \
    rsyslog \
    openssh-client \
    openssh-server \
    tar \
    gdb \
    sudo \
    && apt-get purge -y --allow-remove-essential --allow-change-held-packages \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && grep ^postgres: /etc/group || groupadd postgres \
    && grep ^postgres: /etc/passwd && usermod -s /bin/bash postgres \
    || useradd -M -N -g postgres -r -d /var/lib/postgresql -s /bin/bash -c "Postgres Pro Server" postgres 

#RUN echo 'eval "$(ssh-agent -s)"' >> .bashrc && echo 'ssh-add /var/lib/postgresql/.ssh/id_rsa' >> .bashrc
