FROM {{ ImageUbuntu }}

ARG PG_MAJOR={{ PgMajorVersion }}
ENV APP /opt/pgpro/sdm-$PG_MAJOR

RUN mkdir -p /etc/systemd/system/systemd-logind.service.d /etc/shardman /build /mntdata /tmp && chmod -R 0777 /mntdata

RUN apt-get autoclean -y && apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends gnupg \
    curl \
    ca-certificates \
    vim \
    gnupg \
    systemd-sysv \
    systemd \
    libev4 \
    libicu-dev \
    libldap-dev \
    libpam0g \
    libssl-dev \
    libxml2 \
    tzdata \
    ssl-cert \
    libldap2-dev \
    locales \
    dbus-x11 \
    make \
    libipc-run-perl \
    libreadline8 \
    pkg-config \
    net-tools \
    zlib1g \
    git \
    rsyslog \
    openssh-client \
    openssh-server \
    libossp-uuid-dev \
    tar \
    gdb \
    gdb-multiarch \
    sudo \
    libcurl4-nss-dev \
    libcurl4 \
    telnet \
    libxslt-dev \
    libxml2-dev \
    iproute2 \
    less \
    && apt-get purge -y --allow-remove-essential --allow-change-held-packages \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && grep ^postgres: /etc/group || groupadd postgres \
    && grep ^postgres: /etc/passwd && usermod -s /bin/bash postgres \
    || useradd -M -N -g postgres -r -d /var/lib/postgresql -s /bin/bash -c "Postgres Pro Server" postgres 

#RUN echo 'eval "$(ssh-agent -s)"' >> .bashrc && echo 'ssh-add /var/lib/postgresql/.ssh/id_rsa' >> .bashrc
